### PR TITLE
Merge pull request #1 from stat4701/gh-pages

### PR DESCRIPTION
**Pull request by sg2928**
Merge from upstream

### CODE REVIEW

**Comment by sg2928** [comment]
Merge

**Comment by malecki** [comment]
wrong direction ;) the whole like 5-step pr-to-self thing is cool, but I always just do 
```
git fetch upstream
git merge upstream/gh-pages
git push
```
:bamboo:

**Comment by sg2928** [comment]
Thanks Mike. I hope, I did not mess up. Can I follow these steps now?

**Comment by malecki** [comment]
yup :+1:

**Comment by sg2928** [comment]
Hello Mike,
How are you?
Did you get a chance to request on sg2928_blogpost branch?

**Pull request closed without merging**
