### PR TITLE
TestBlog

### PR DESCRIPTION
**Pull request by fullmogra**

### CODE REVIEW

**Comment by malecki** [comment]
jekyll really likes everything in `_posts/` to have a date

**Comment by fullmogra** [comment]
oh yea.  doing it now.  thank you.

**Comment by fullmogra** [comment]
Hi Mike, do you see my .md file in the same branch <presentation>?

**Comment by malecki** [comment]
I’m going to go ahead and merge this but you will see it is not exactly right — you can continue to push on this branch and open a new pull request for subsequent changes.

**Comment by malecki** [comment]
please merge from upstream so the addition of `Thumbs.db` is added to your `.gitignore`

**Comment by fullmogra** [comment]
Thanks.
I am just trying to see if I can view the page but I don;t know how to view
it?

http://fullmogra.github.io/edav/

Can you please give some guidance?
thanks,
--Aarti

**Comment by fullmogra** [comment]
I see my file - when opened has lots of Errors!!  :(.

More work to do.

**Pull request merged**
