### PR TITLE
Denys Liubyvyi HW

### PR DESCRIPTION
**Pull request by denniskorablev**

### CODE REVIEW

**Comment by malecki** [comment]
could you cherry-pick e8b06e7..dbc8928 onto a new branch based on upstream/gh-pages?
```
git fetch upstream
git checkout upstream/gh-pages # detached HEAD
git checkout -b r-mini-assign # new branch on which to place the commits
git cherry-pick e8b06e7..dbc8928
git push origin r-mini-assign
```
& then open a new pr which only contains those please

**Comment by denniskorablev** [comment]
fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by denniskorablev** [comment]
What should I do?
Thank you

**Comment by malecki** [comment]
to define it:
`git remote add upstream https://github.com/stat4701/edav.git`

**Pull request closed without merging**
